name: Deploy to Azure from GHCR

on:
  registry_package:
    types: [updated,published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    #if: github.event.registry_package.package.name == 'address-service'
    steps:
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'arts-admin'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ghcr.io/I tndph-arts/address-service:${{ github.sha }}'
